#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include "../lib/libft/libft.h"
#include <readline/readline.h>
#include <readline/history.h>
#include <sys/types.h>
